module.exports = [
    {
      name: "Affogato al Caffé",
      alternate_names: "Affogato",
      country_of_origin: "Italy",
      type: "Cold",
      coffee_base: "espresso",
      main_ingredients: "Coffee, Ice Cream",
      similar_drinks: "Eiskaffee",
      preparation: "Pour a shot of hot espresso over vanilla ice cream or gelato. Can include a shot of Amaretto or other liquor.",
      taste: "Creamy, bittersweet",
      notes: "An affogato is usually presented in a clear glass for visual effect. To prevent melting, mixing is done at the table.",
      img: "https://www.thespruceeats.com/thmb/68fCSNbj5S4MFZPNFimHJbQY9co=/1500x1000/filters:fill(auto,1)/affogato-4776668-hero-08-40d7a68d12ba46f48eaea3c43aba715c.jpg"
    },
    {
      name: "Bicerin",
      alternate_names: "",
      country_of_origin: "Italy",
      type: "Hot",
      coffee_base: "espresso",
      main_ingredients: "coffee, chocolate, cream",
      similar_drinks: "espressino, marocchino",
      preparation: "Use equal parts espresso, hot chocolate, and hot cream in that order. Do not stir",
      taste: "bitter, creamy, strong",
      notes: "a bicerin is served layered in a glass",
      img: "https://www.eataly.com/wp/wp-content/uploads/2018/11/2018_11_November_Bicerin_05.jpg"
    },
    {
      name: "Black Eye",
      alternate_names: "",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Drip-brew, espresso",
      main_ingredients: "Coffee",
      similar_drinks: "red eye, dead eye",
      preparation: "pour two shots of espresso over a cup of coffee",
      taste: "strong",
      notes: "SAMPLE TEXT",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnWdEbz8T7niAT2E1JNZKLuLl3VbdMUX7t3g&usqp=CAU"
    },
    {
      name: "Black Tie",
      alternate_names: "",
      country_of_origin: "Thailand",
      type: "Cold",
      coffee_base: "Espresso",
      main_ingredients: "coffee, black tea, sugar, milk",
      similar_drinks: "Dirty Chai",
      preparation: "combine chilled tea with two shots of espresso and other ingredients. Also include: orange blossom water, star anise, tamarind",
      taste: "bitter, spicy, sweet",
      notes: "asdf",
      img: "https://blog.lovers.coffee/wp-content/uploads/2021/04/ben-kolde-sKBWdCyBLg-unsplash.jpg"
    },
    {
      name: "Ca Phe",
      alternate_names: "Vietnamese Coffee",
      country_of_origin: "Vietnam",
      type: "Hot",
      coffee_base: "French Press",
      main_ingredients: "coffee, condensed milk, sugar",
      similar_drinks: "Cuban Espresso, Indian Filter Coffee",
      preparation: "use sweetened condensed milk",
      taste: "creamy, strong, sweet",
      notes: "",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIAsLyLoXelQb1Hlqr06SIEx15ZbLKcdCi3g&usqp=CAU"
    },
    {
      name: "Ca Phe Sua Da",
      alternate_names: "Vietnamese Iced Coffee",
      country_of_origin: "Vietnam",
      type: "Cold",
      coffee_base: "French Press",
      main_ingredients: "coffee, condensed milk, sugar",
      similar_drinks: "Thai Iced Tea",
      preparation: "Use a quarter to half as much sweetened condensed milk as coffee",
      taste: "creamy, strong, sweet",
      notes: "The sweetness in Vietnamese Iced Coffee comes more from the condensed milk than sugar. Vietnamese coffee is made with a traditional Vietnamese filter, similar to a French press, that gives it a different taste than drip machines.",
      img: "https://img.taste.com.au/UHFv39Ks/taste/2020/05/jun20_vietnamese-iced-coffee-161761-1.jpg"}
  ]
