module.exports = [
    {
      name: "Affogato al Caffé",
      alternate_names: "Affogato",
      country_of_origin: "Italy",
      type: "Cold",
      coffee_base: "espresso",
      main_ingredients: "Coffee, Ice Cream",
      similar_drinks: "Eiskaffee",
      preparation: "Pour a shot of hot espresso over vanilla ice cream or gelato. Can include a shot of Amaretto or other liquor.",
      taste: "Creamy, bittersweet",
      notes: "An affogato is usually presented in a clear glass for visual effect. To prevent melting, mixing is done at the table.",
      img: "https://www.thespruceeats.com/thmb/68fCSNbj5S4MFZPNFimHJbQY9co=/1500x1000/filters:fill(auto,1)/affogato-4776668-hero-08-40d7a68d12ba46f48eaea3c43aba715c.jpg"
    },
    {
      name: "Bicerin",
      alternate_names: "",
      country_of_origin: "Italy",
      type: "Hot",
      coffee_base: "espresso",
      main_ingredients: "coffee, chocolate, cream",
      similar_drinks: "espressino, marocchino",
      preparation: "Use equal parts espresso, hot chocolate, and hot cream in that order. Do not stir",
      taste: "bitter, creamy, strong",
      notes: "a bicerin is served layered in a glass",
      img: "https://www.eataly.com/wp/wp-content/uploads/2018/11/2018_11_November_Bicerin_05.jpg"
    },
    {
      name: "Black Eye",
      alternate_names: "",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Drip-brew, espresso",
      main_ingredients: "Coffee",
      similar_drinks: "red eye, dead eye",
      preparation: "pour two shots of espresso over a cup of coffee",
      taste: "strong",
      notes: "",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnWdEbz8T7niAT2E1JNZKLuLl3VbdMUX7t3g&usqp=CAU"
    },
    {
      name: "Black Tie",
      alternate_names: "",
      country_of_origin: "Thailand",
      type: "Cold",
      coffee_base: "Espresso",
      main_ingredients: "coffee, black tea, sugar, milk",
      similar_drinks: "Dirty Chai",
      preparation: "combine chilled tea with two shots of espresso and other ingredients. Also include: orange blossom water, star anise, tamarind",
      taste: "bitter, spicy, sweet",
      notes: "asdf",
      img: "https://lovekitchentoday.com/wp-content/uploads/2017/11/Black-Tie-Coffee-recipe.jpg"
    },
    {
      name: "Ca Phe",
      alternate_names: "Vietnamese Coffee",
      country_of_origin: "Vietnam",
      type: "Hot",
      coffee_base: "French Press",
      main_ingredients: "coffee, condensed milk, sugar",
      similar_drinks: "Cuban Espresso, Indian Filter Coffee",
      preparation: "use sweetened condensed milk",
      taste: "creamy, strong, sweet",
      notes: "",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIAsLyLoXelQb1Hlqr06SIEx15ZbLKcdCi3g&usqp=CAU"
    },
    {
      name: "Ca Phe Sua Da",
      alternate_names: "Vietnamese Iced Coffee",
      country_of_origin: "Vietnam",
      type: "Cold",
      coffee_base: "French Press",
      main_ingredients: "coffee, condensed milk, sugar",
      similar_drinks: "Thai Iced Tea",
      preparation: "Use a quarter to half as much sweetened condensed milk as coffee",
      taste: "creamy, strong, sweet",
      notes: "The sweetness in Vietnamese Iced Coffee comes more from the condensed milk than sugar. Vietnamese coffee is made with a traditional Vietnamese filter, similar to a French press, that gives it a different taste than drip machines.",
      img: "https://img.taste.com.au/UHFv39Ks/taste/2020/05/jun20_vietnamese-iced-coffee-161761-1.jpg"
    },
    {
      name: "Café au Lait",
      alternate_names: "",
      country_of_origin: "France",
      type: "Hot",
      coffee_base: "Drip-brew, French Press",
      main_ingredients: "coffee, milk",
      similar_drinks: "Café con Leche, Caffé Latte, Flat White",
      preparation: "Steamed milk is added to coffee",
      taste: "Milky",
      notes: "A Café au Lait is sometimes served in a bowl as is tradition in France. Presentation may be similar to latte with art but fainter.",
      img: "https://media-cdn.tripadvisor.com/media/photo-s/19/f0/e6/ef/cafe-au-lait.jpg"      
    },
    {
      name: "Café Bombón",
      alternate_names: "",
      country_of_origin: "Spain",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, condensed milk",
      similar_drinks: "",
      preparation: "Slowly add sweetened condensed milk to espresso in equal parts",
      taste: "Bitter, creamy, sweet",
      notes: "A Café Bombón is usually served layered in a glass, then mixed before being consumed",
      img: "https://www.lorespresso.com/media/wysiwyg/LOR_content/Pages/Receipes/_resized/bonbonskoffie640x450-534x375.jpg"     
    },
    {
      name: "Café Brûlot",
      alternate_names: "Café Diablo, Café Diabolique, Devil's Coffee",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Drip-brew",
      main_ingredients: "Brandy, cinnamon, cloves, coffee, lemon peel, orange peel, sugar",
      similar_drinks: "Liqueur coffee",
      preparation: "Heat brandy in a sauce pan, then light on fire. Add brandy to other ingredients, stirring in coffee last to douse flames",
      taste: "Citrusy, rich, spicy, strong, sweet ",
      notes: "A Café Brulot is  prepared in front of the customer, a theatrical affair as the brandy is ignited and mixed into the other ingredients. The drink is  served in a cup and saucer set, usually demitasse or brulot cups",
      img: "https://assets-prd.punchdrink.com/wp-content/uploads/2020/02/12134701/Article-Recipe-Dale-DeGroff-King-Cocktail-Cafe-Brulot-Cocktail-Recipe.jpg"   
    },
    {
      name: "Café con Leche",
      alternate_names: "",
      country_of_origin: "Spain",
      type: "Hot",
      coffee_base: "Drip-brew",
      main_ingredients: "Coffee, milk",
      similar_drinks: "Café au Lait, Caffe Latte, Flat White",
      preparation: "Scalded milk is added to coffee in equal parts.",
      taste: "Milky",
      notes: "Café con Leche has a simple presentation in a mug and saucer",
      img: "https://media.istockphoto.com/photos/after-dinner-cafe-au-lait-uno-con-leche-picture-id140379296?k=20&m=140379296&s=612x612&w=0&h=toOxjHGv8T2ImaOuOLb4HAQhi1WaGwD_lt9zZE7GM6Y="   
    },
    {
      name: "Caffé Mocha",
      alternate_names: "Moccacino",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, chocolate, milk",
      similar_drinks: "Mocha Latte, Bicerin",
      preparation: "Add either sweet cocoa powder or chocolate syrup to a shot of espresso. Follow with steamed milk and foam",
      taste: "Bittersweet, milky, chocolatey",
      notes: "A Caffe Mocha is served in a tall glass or mug. Whipped cream can be added instead of foam. ",
      img: "https://easyweeknightrecipes.com/wp-content/uploads/2020/08/Mocha-Iced-Coffee-5.jpg"   
    },
    {
      name: "Caffé Americano",
      alternate_names: "Americano, Café Americano",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, water",
      similar_drinks: "Long Black",
      preparation: "Add hot water to espresso, usually at a ratio of 3:1.",
      taste: "Strong",
      notes: "A Caffe Americano is similar in strength to drip-brew coffee but has the intense flavor of an espresso. It is traditionally served in a mug and mixed before consuming",
      img: "https://www.nespresso.com/ncp/res/uploads/recipes/nespresso-recipes-Americano-by-Nespresso.jpg"   
    },
    {
      name: "Caffé Breve",
      alternate_names: "Breve, Café Breve",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, half-and-half",
      similar_drinks: "Caffe Latte",
      preparation: "Add steamed half-and-half to a shot of espresso with a layer of foam.",
      taste: "Creamy, rich",
      notes: "A caffe breve is served similar to a caffe latte, including art",
      img: "https://www.ecooe.com/ecooe-life/wp-content/uploads/2016/08/flatwhite-coffee.jpg"   
    },
    {
      name: "Caffé Latte",
      alternate_names: "Latte",
      country_of_origin: "Italy",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, milk",
      similar_drinks: "Flat white, café au lait, café con leche,  café com leite",
      preparation: "Add steamed milk to a shot of espresso at a ratio of at least 2:1 with a layer of foam on top",
      taste: "Milky",
      notes: "Lattes are usually served in a large mug and are widely known for their art",
      img: "https://media.istockphoto.com/photos/caffe-latte-macchiato-coffee-layered-with-milk-picture-id1092652322?k=20&m=1092652322&s=170667a&w=0&h=zAdM5OPZSXE9beHEkmbA9v0wEZsM0cczYLaZ2npLhDc=" 
    },
    {
      name: "Caffé Macchiato",
      alternate_names: "Espresso Macchiato, Macchiato",
      country_of_origin: "Italy",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, milk",
      similar_drinks: "Espresso",
      preparation: "AAdd a small amount of steamed or frothed milk to two shots of espresso",
      taste: "Bitter, strong",
      notes: "A Caffe Macchiato is presented similar to an espresso and can have art like a caffe latte",
      img: "https://media.istockphoto.com/photos/cafe-latte-macchiato-layered-coffee-picture-id1256257189?k=20&m=1256257189&s=612x612&w=0&h=8HHukdwHZyM6ngar_NT0fY2E3UcmfTb8U4At52cS17k=" 
    },
    {
      name: "Caffé Marocchino",
      alternate_names: "Marocchino",
      country_of_origin: "Italy",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, cocoa, milk",
      similar_drinks: "Bicerin",
      preparation: "Add a small amount of hot milk to a shot of espresso. Top with cocoa powder",
      taste: "Milky, strong, chocolatey",
      notes: "A Caffe Marocchino is served layered in a small glass. It can also be prepared with a dusting of cocoa powder at the bottom of the cup",
      img: "https://perfectdailygrind.com/wp-content/uploads/2020/11/Cafe%CC%81-Marrochino-4.jpg" 
    },
    {
      name: "Cappuccino",
      alternate_names: "",
      country_of_origin: "Italy",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, milk",
      similar_drinks: "Caffe Latte",
      preparation: "Use equal parts espresso, steamed milk, and foam in that order",
      taste: "Milky, strong",
      notes: "Usually served in a mug",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKxbY-L3qqgWkJbkFF019F69a23FDldwZeGQ&usqp=CAU" 
    },
    {
      name: "Cold-Brewed Iced Coffee",
      alternate_names: "",
      country_of_origin: "",
      type: "Cold",
      coffee_base: "Cold-brew",
      main_ingredients: "Coffee",
      similar_drinks: "Iced Coffee",
      preparation: "Add one part concentrated coffee to three parts water to a glass filled with ice",
      taste: "Smooth, flavorful, sweet",
      notes: "Cold-brewed coffee is less acidic, has less caffeine and bitterness, and has a smoother flavor than drip-brewed coffee",
      img: "https://assets.bonappetit.com/photos/57ad43f91b3340441497558f/5:7/w_1375,h_1925,c_limit/dublin-iced-coffee.jpg" 
    },
    {
      name: "Café Cubano",
      alternate_names: "Cuban Coffee, Cuban Espresso",
      country_of_origin: "Cuba",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Coffee, sugar",
      similar_drinks: "Cortadito, Café con Leche, Ca Phe",
      preparation: "Add sugar to the container where espresso is dripped",
      taste: "Sweet, strong",
      notes: "In a Café Cubano, mixing the espresso with sugar while it brews gives a sweeter and smoother flavor than mixing sugar after brewing",
      img: "https://www.thespruceeats.com/thmb/xhjEXST5ToDhB3gFzCx6ZT5N3WI=/4000x2667/filters:no_upscale()/CubanCoffee-001-4928e640d5b7491aa223fb594285a3bf.jpg" 
    },
    {
      name: "Dirty Chai Latte",
      alternate_names: "",
      country_of_origin: "United States",
      type: "Hot",
      coffee_base: "Espresso",
      main_ingredients: "Black tea, coffee, milk, cinnamon",
      similar_drinks: "Black Tie",
      preparation: "Add a shot of espresso to a black tea with milk",
      taste: "Sweet, spicy, strong",
      notes: "Preparation is similar to a Caffe Latte",
      img: "https://images.squarespace-cdn.com/content/v1/56b0bf2c8259b50fa9157b85/1588242596618-1JQC9CPVBIUNZEZQLWJ7/Dirty-Chai-Latte-FB2.jpg" 
    },
    {
      name: "Eiskaffee",
      alternate_names: "German Iced Coffee",
      country_of_origin: "Germany",
      type: "Cold",
      coffee_base: "Drip-brew",
      main_ingredients: "Coffee, ice cream, whipped cream",
      similar_drinks: "Black Tie",
      preparation: "Add a shot of espresso to a black tea with milk",
      taste: "Sweet, spicy, strong",
      notes: "Preparation is similar to a Caffe Latte",
      img: "https://images.squarespace-cdn.com/content/v1/56b0bf2c8259b50fa9157b85/1588242596618-1JQC9CPVBIUNZEZQLWJ7/Dirty-Chai-Latte-FB2.jpg" 
    }
  ]
